### ISSUE TITLE
Getting Error while loading of fusioncharts. 

### ISSUE THREAD

**Issue by Nsingh0007** [fusioncharts/react-fusioncharts-component#80]
Uncaught (in promise) ChunkLoadError: Loading chunk 13 failed.
(missing: http://localhost:3000/fusioncharts.excelexport.js)
    at a.e (fusioncharts.js:13:1)
    at Function.<anonymous> (fusioncharts.js:13:1)
    at i (fusioncharts.js:13:1)
    at o (fusioncharts.js:13:1)
    at d (fusioncharts.js:13:1)
    at t.fireEvent (fusioncharts.js:13:1)
    at t.preConfigure (fusioncharts.js:13:1)
    at r.preConfigure (fusioncharts.js:14:1)
    at t.preConfigure (fusioncharts.js:299:1)
    at t.configure (fusioncharts.js:13:1)

**Comment by thekingofbandit** [comment]
please check if you import this way:

```
import React from "react";
import FusionCharts from "fusioncharts";
import Charts from "fusioncharts/fusioncharts.charts";
import ReactFC from "react-fusioncharts";
import ExcelExport from "fusioncharts/fusioncharts.excelexport";
import FusionTheme from 'fusioncharts/themes/fusioncharts.theme.fusion';

ReactFC.fcRoot(FusionCharts, Charts, ExcelExport,FusionTheme);
```

before I import like this, which is throwing same error as you shown above.

```
import React from "react";
import FusionCharts from "fusioncharts";
import charts from "fusioncharts/fusioncharts.charts";
import ReactFusioncharts from "react-fusioncharts";

// Resolves charts dependancy
charts(FusionCharts);
```
